// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmIjvBcGoGD_EbvHuprC-54FNHzAfrdAE',
    appId: '1:27292719597:web:4e7d98f39d9db2af56efe4',
    messagingSenderId: '27292719597',
    projectId: 'trying-firebase-5d0f8',
    authDomain: 'trying-firebase-5d0f8.firebaseapp.com',
    storageBucket: 'trying-firebase-5d0f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjptX0x2hnPJBxame2QFIZtm3K4iAYo2o',
    appId: '1:27292719597:android:e32278468967113856efe4',
    messagingSenderId: '27292719597',
    projectId: 'trying-firebase-5d0f8',
    storageBucket: 'trying-firebase-5d0f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAypbBFpCsxKzMiyI1zf7JPuWmbKqGYOoU',
    appId: '1:27292719597:ios:c0eff2e7a8347d3b56efe4',
    messagingSenderId: '27292719597',
    projectId: 'trying-firebase-5d0f8',
    storageBucket: 'trying-firebase-5d0f8.firebasestorage.app',
    iosClientId: '27292719597-l73fo99l8g4k2qhnm44p14e0kqdoqmlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAypbBFpCsxKzMiyI1zf7JPuWmbKqGYOoU',
    appId: '1:27292719597:ios:c0eff2e7a8347d3b56efe4',
    messagingSenderId: '27292719597',
    projectId: 'trying-firebase-5d0f8',
    storageBucket: 'trying-firebase-5d0f8.firebasestorage.app',
    iosClientId: '27292719597-l73fo99l8g4k2qhnm44p14e0kqdoqmlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmIjvBcGoGD_EbvHuprC-54FNHzAfrdAE',
    appId: '1:27292719597:web:d825df509947f03356efe4',
    messagingSenderId: '27292719597',
    projectId: 'trying-firebase-5d0f8',
    authDomain: 'trying-firebase-5d0f8.firebaseapp.com',
    storageBucket: 'trying-firebase-5d0f8.firebasestorage.app',
  );

}